site_name: 夜独整合包 Wiki
site_url: https://oiclyd.github.io/bg3-mod-wiki

theme:
  name: material
  language: zh
  palette:
    - scheme: slate
      primary: amber
      accent: amber
  font:
    text: Noto Sans SC
    code: JetBrains Mono
  features:
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
  custom_dir: overrides
  extra_css:
    - stylesheets/extra.css

plugins:
  - search:
      lang: zh

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - tables
  - toc:
      permalink: true
      toc_depth: 2

nav:
  - 首页: index.md
  - 新手入门: ch1-start.md
  - 使用指南: ch2-mod.md
  - 常见问题: ch3-faq.md
  - 职业攻略: ch4-class.md
  - 种族攻略: ch6-race.md
  - 专长攻略: ch7-divinity.md
  - 装备攻略: ch8-equip.md
  - 任务攻略:
      - 任务攻略: ch10-quest.md
      - 亡灵之路（血径）: ch9-bloodtrail.md
  - 进化攻略: ch9-summon.md
  - 难度攻略: ch11-difficulty.md
  - 炼金攻略: ch12-alchemy.md
  - 自选模组: ch10-mod.md

extra:
  social:
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/16303982
      name: B站主页
  generator: false

copyright: |
  &copy; 2024 在下夜独 | 
  <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY-NC-SA 4.0</a>
