site_name: 夜独整合包 Wiki
site_url: https://oiclyd.github.io/bg3-mod-wiki

theme:
  name: material
  language: zh
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: amber
      accent: amber
      toggle:
        icon: material/brightness-7
        name: 切换到深色模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: amber
      accent: amber
      toggle:
        icon: material/brightness-4
        name: 切换到浅色模式
  font:
    text: Noto Sans SC
    code: JetBrains Mono
  features:
    - navigation.top

plugins:
  - search:
      lang: zh

markdown_extensions:
  - tables
  - toc:
      permalink: true
      toc_depth: 2

nav:
  - 首页: index.md
  - 新手入门: ch1-start.md
  - MOD工具与教程: ch2-mod.md
  - 常见问题汇总: ch3-faq.md
  - 职业攻略: ch4-class.md
  - 种族攻略: ch6-race.md
  - 专长攻略: ch7-divinity.md
  - 装备攻略: ch8-equip.md
  - 召唤攻略: ch9-summon.md
  - 自选模组说明: ch10-mod.md
  - 难度攻略: ch11-difficulty.md
  - 炼金术: ch12-alchemy.md
